### ISSUE TITLE
Proposal for improvements

### ISSUE THREAD

**Issue by rogarb** [echo-devim/huextract#1]
I started working on improving this program:
 - added a more comprehensive UI with clap, which provides out of the box --help switch for example
 - lot of code refactoring (with different crate level types and the corresponding methods)
 - added checksum verification when extracting img files
 - added pretty displaying of img headers in the UPDATE.APP file
 - some other stuff (see --help for details)

I also plan to add a README.md file.

FYI, I removed multithreaded extraction of the files as IMO, the bottleneck is not the CPU but the disk IO, which is not improved by multithreading (which I verified at some point when benchmarking the extraction time for the single threaded version and the huextract.bin file present in the repo). It can be added back, and activated through a command line switch for example.

All the work can be checked at https://github.com/rogarb/huextract/tree/v2.0, I can create a PR if it is of interest to you.

**Comment by echo-devim** [comment]
I made this tool just to experiment a little bit with Rust, I'm not working on this project anymore. If you want to make a PR, I'm going to accept it. Otherwise you can keep your forked project and move forward in the development.

Thank you for your interest :)

**Comment by rogarb** [comment]
Great, I'll send a PR when I am happy with my code.

**Comment by rogarb** [comment]
Thank you for merging.

I might come up again with some smaller improvements, I'll be pushing them to the devel branch of my fork.
